#!/usr/bin/env python3
"""Render README routing tables from OpenConfig's canonical JSON sources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROUTING_START = "<!-- BEGIN GENERATED: runtime-routing -->"
ROUTING_END = "<!-- END GENERATED: runtime-routing -->"
SCAFFOLD_START = "<!-- BEGIN GENERATED: scaffold-profiles -->"
SCAFFOLD_END = "<!-- END GENERATED: scaffold-profiles -->"
PROFILE_ORDER = ("high", "low", "fast", "research", "debug", "writing", "content-aware")


def load_object(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"expected a JSON object: {path}")
    return data


def code(value: object) -> str:
    return f"`{value}`" if isinstance(value, str) and value else "—"


def runtime_routing(repo: Path) -> str:
    data = load_object(repo / "runtime-profile.json")
    profiles = {}
    for profile in ("normal", "pentest"):
        selected = data.get(profile)
        if not isinstance(selected, dict):
            raise SystemExit(f"runtime-profile.json missing {profile!r}")
        profiles[profile] = selected

    lines = [
        ROUTING_START,
        "<!-- Generated by scripts/render-routing-docs.py; do not edit this block manually. -->",
        "| Route | Normal primary | Pentest primary |",
        "| --- | --- | --- |",
    ]
    for section in ("agents", "categories"):
        names = sorted(
            set((profiles["normal"].get(section) or {}))
            | set((profiles["pentest"].get(section) or {}))
        )
        for name in names:
            normal = ((profiles["normal"].get(section) or {}).get(name) or {}).get("model")
            pentest = ((profiles["pentest"].get(section) or {}).get(name) or {}).get("model")
            lines.append(f"| `{section}.{name}` | {code(normal)} | {code(pentest)} |")
    lines.extend(
        [
            "",
            "Fallback order and reasoning remain machine-readable through "
            "`oc profile resolve <normal|pentest> <agents|categories> <name>`.",
            ROUTING_END,
        ]
    )
    return "\n".join(lines)


def scaffold_profiles(repo: Path) -> str:
    profiles_dir = repo / "profiles"
    discovered = {path.stem for path in profiles_dir.glob("*.json")}
    ordered = [name for name in PROFILE_ORDER if name in discovered]
    ordered.extend(sorted(discovered - set(ordered)))
    lines = [
        SCAFFOLD_START,
        "<!-- Generated by scripts/render-routing-docs.py; do not edit this block manually. -->",
        "| Profile | Default agent | Main model | Small model |",
        "| --- | --- | --- | --- |",
    ]
    for name in ordered:
        profile = load_object(profiles_dir / f"{name}.json")
        lines.append(
            f"| `{name}` | {code(profile.get('default_agent'))} | "
            f"{code(profile.get('model'))} | {code(profile.get('small_model'))} |"
        )
    lines.extend([SCAFFOLD_END])
    return "\n".join(lines)


def replace_block(text: str, start: str, end: str, rendered: str) -> str:
    if text.count(start) != 1 or text.count(end) != 1:
        raise SystemExit(f"README must contain exactly one {start!r}/{end!r} block")
    before, remainder = text.split(start, 1)
    _, after = remainder.split(end, 1)
    return before + rendered + after


def expected_readme(repo: Path) -> str:
    path = repo / "README.md"
    current = path.read_text(encoding="utf-8")
    current = replace_block(current, ROUTING_START, ROUTING_END, runtime_routing(repo))
    return replace_block(current, SCAFFOLD_START, SCAFFOLD_END, scaffold_profiles(repo))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", default=str(Path(__file__).resolve().parents[1]))
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--print", dest="print_section", choices=("routing", "profiles"))
    args = parser.parse_args()
    if sum(bool(value) for value in (args.check, args.write, args.print_section)) != 1:
        parser.error("choose exactly one of --check, --write, or --print")

    repo = Path(args.repo).expanduser().resolve()
    if args.print_section == "routing":
        print(runtime_routing(repo))
        return 0
    if args.print_section == "profiles":
        print(scaffold_profiles(repo))
        return 0

    path = repo / "README.md"
    current = path.read_text(encoding="utf-8")
    expected = expected_readme(repo)
    if args.check:
        if current != expected:
            print("README generated routing blocks are stale; run scripts/render-routing-docs.py --write", file=sys.stderr)
            return 1
        print("README generated routing blocks are current")
        return 0
    if current != expected:
        path.write_text(expected, encoding="utf-8")
        print("README generated routing blocks updated")
    else:
        print("README generated routing blocks already current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
